#!/usr/bin/env php
<?php

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\DriverManager;

require __DIR__ . '/vendor/autoload.php';

$settings = require __DIR__ . '/config/settings.php';
$connection = DriverManager::getConnection($settings['settings']['doctrine']['connection']);
$queryBuilder = $connection->createQueryBuilder();

$file = trim($argv[1]);

if(!file_exists($file)) {
    echo "ERROR: File not found\n";
    exit;
}

$fileExtension = pathinfo($file, PATHINFO_EXTENSION);
if($fileExtension !== 'csv') {
    echo "ERROR: File must be in csv format\n";
    exit;    
}

echo "Importing from file: $file\n" ;

$users = [];
$row = 0;
$headers = [];
$discarded = 0;

if (($handle = fopen($file, "r")) !== FALSE) {
    while (($data = fgetcsv($handle, NULL, ",")) !== FALSE) {
        if($row === 0) {
            $headers = $data;
        } else {
            foreach($data as $key => $value) {
                $users[$row][$headers[$key]] = $value;
            }   
        }
        $row++;
    }
    fclose($handle);
}


// insert users
$imported = 0;
foreach($users as $user) {
    try {
        $connection->insert('users', [
            'first_name' => $user['firstName'],
            'last_name' => $user['lastName'],
            'email' => $user['email'],
            'username' => $user['username'],
            'password' => password_hash($user['password'], PASSWORD_BCRYPT),
            'birthday' => $user['birthday'] ?? null
        ]);
        $imported++;
    } catch(Exception $e) {
        echo "ERROR: " . $e->getMessage() . "\n";
        $discarded++;
    }
}


echo "Done importing from file" . PHP_EOL;
echo "User imported: " . strval($imported) . PHP_EOL;
echo "User discarded: " . strval($discarded) . PHP_EOL;